--- #YAML:1.0
name:               DBD-SQLite
version:            1.19_09
abstract:           Self Contained SQLite RDBMS in a DBI Driver
author:
    - Adam Kennedy <adamk@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    DBI:                  1.43
    ExtUtils::MakeMaker:  6.48
    File::Spec:           0.82
build_requires:
    Test::More:        0.42
    Test::NoWarnings:  0.081
requires:
    DBI:               1.43
    perl:              5.006
    Test::More:        0.42
    Test::NoWarnings:  0.081
resources:
    bugtracker:   http://rt.cpan.org/NoAuth/ReportBug.html?Queue=DBD-SQLite
    license:      http://dev.perl.org/licenses/
    MailingList:  http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/dbd-sqlite
    repository:   http://svn.ali.as/cpan/trunk/DBD-SQLite
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
