#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBD-SQLite
version:      0.29
version_from: lib/DBD/SQLite.pm
installdirs:  site
requires:
    DBI:                           1.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
