#define TK_ABORT                           1
#define TK_AGG_FUNCTION                    2
#define TK_ALL                             3
#define TK_AND                             4
#define TK_AS                              5
#define TK_ASC                             6
#define TK_BEGIN                           7
#define TK_BETWEEN                         8
#define TK_BITAND                          9
#define TK_BITNOT                         10
#define TK_BITOR                          11
#define TK_BY                             12
#define TK_CASE                           13
#define TK_CHECK                          14
#define TK_CLUSTER                        15
#define TK_COLUMN                         16
#define TK_COMMA                          17
#define TK_COMMENT                        18
#define TK_COMMIT                         19
#define TK_CONCAT                         20
#define TK_CONFLICT                       21
#define TK_CONSTRAINT                     22
#define TK_COPY                           23
#define TK_CREATE                         24
#define TK_DEFAULT                        25
#define TK_DELETE                         26
#define TK_DELIMITERS                     27
#define TK_DESC                           28
#define TK_DISTINCT                       29
#define TK_DOT                            30
#define TK_DROP                           31
#define TK_ELSE                           32
#define TK_END                            33
#define TK_END_OF_FILE                    34
#define TK_EQ                             35
#define TK_EXCEPT                         36
#define TK_EXPLAIN                        37
#define TK_FAIL                           38
#define TK_FLOAT                          39
#define TK_FROM                           40
#define TK_FUNCTION                       41
#define TK_GE                             42
#define TK_GLOB                           43
#define TK_GROUP                          44
#define TK_GT                             45
#define TK_HAVING                         46
#define TK_ID                             47
#define TK_IGNORE                         48
#define TK_ILLEGAL                        49
#define TK_IN                             50
#define TK_INDEX                          51
#define TK_INSERT                         52
#define TK_INTEGER                        53
#define TK_INTERSECT                      54
#define TK_INTO                           55
#define TK_IS                             56
#define TK_ISNULL                         57
#define TK_KEY                            58
#define TK_LE                             59
#define TK_LIKE                           60
#define TK_LIMIT                          61
#define TK_LP                             62
#define TK_LSHIFT                         63
#define TK_LT                             64
#define TK_MINUS                          65
#define TK_NE                             66
#define TK_NOT                            67
#define TK_NOTNULL                        68
#define TK_NULL                           69
#define TK_OFFSET                         70
#define TK_ON                             71
#define TK_OR                             72
#define TK_ORDER                          73
#define TK_PLUS                           74
#define TK_PRAGMA                         75
#define TK_PRIMARY                        76
#define TK_REM                            77
#define TK_REPLACE                        78
#define TK_ROLLBACK                       79
#define TK_RP                             80
#define TK_RSHIFT                         81
#define TK_SELECT                         82
#define TK_SEMI                           83
#define TK_SET                            84
#define TK_SLASH                          85
#define TK_SPACE                          86
#define TK_STAR                           87
#define TK_STRING                         88
#define TK_TABLE                          89
#define TK_TEMP                           90
#define TK_THEN                           91
#define TK_TRANSACTION                    92
#define TK_UMINUS                         93
#define TK_UNCLOSED_STRING                94
#define TK_UNION                          95
#define TK_UNIQUE                         96
#define TK_UPDATE                         97
#define TK_USING                          98
#define TK_VACUUM                         99
#define TK_VALUES                         100
#define TK_VIEW                           101
#define TK_WHEN                           102
#define TK_WHERE                          103
